name: Compilação do PDF

on:
  push:
    tags:
      - 'v*.*'

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o código
        uses: actions/checkout@v3

      - name: Compilando latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: monografia.tex

      - name: Renomeando o PDF
        run: mv monografia.pdf monografia-$GITHUB_REF_NAME.pdf

      - name: Publicando PDF
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: monografia-$GITHUB_REF_NAME.pdf